name = "rajendranagar-worker"
main = "worker/worker.js"
compatibility_date = "2024-12-16"

[env.production]
routes = [
  { pattern = "api.rajendranagar.online/*", zone_name = "rajendranagar.online" }
]
vars = { ENVIRONMENT = "production" }

[build]
command = "npm install"
